services:
  # FastAPI
  app:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    container_name: fastapi-app
    env_file:
      - ./api/.env
    depends_on:
      - db
    ports:
      - "8000:8000"

  # React UI
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.ui
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    container_name: ui
    depends_on:
      - app
    ports:
      - "3101:80"

  # React Admin
  ui-admin:
    build:
      context: ./ui-admin
      dockerfile: Dockerfile.ui-admin
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    container_name: ui-admin
    depends_on:
      - app
    ports:
      - "3102:80"

  # Postgres
  db:
    image: postgres:15
    container_name: fastapi-db
    restart: always
    env_file:
      - ./api/.env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
