### Parte do middleware C#
### Registrar usuário com biometria #1
POST http://127.0.0.1:8000/queue/register 
Content-Type: application/json

{
  "user": {
    "name": "Maria Santos",
    "id_number": "9876563LA055",
    "phone": "+244923456789",
    "birth_date": "1995-04-12"
  },
  "biometric": {
    "biometric_id": "c13f9c04-6c88-4bb8-9a7d-0e44fcd6b2c0",
    "finger_index": 2
  }
}

### Registrar usuário com biometria #2
POST http://127.0.0.1:8000/queue/register
Content-Type: application/json

{
  "user": {
    "name": "Luis Lopes",
    "id_number": "9876563LA066",
    "phone": "+244923456789",
    "birth_date": "1995-04-12"
  },
  "biometric": {
    "biometric_id": "c13f9c04-5c66-4bb8-9a7d-0e44fcd6b2c0",
    "finger_index": 1
  }
}

### Registrar usuário com biometria #2
POST http://127.0.0.1:8000/queue/register
Content-Type: application/json

{
  "user": {
    "name": "Francisco Canda",
    "id_number": "00876563LA077",
    "phone": "+244923456789",
    "birth_date": "1995-04-12"
  },
  "biometric": {
    "biometric_id": "c13f9c04-0000-4bb8-9a7d-0e44fcd6b2c0",
    "finger_index": 1
  }
}

### Registrar usuário com biometria #3
POST http://127.0.0.1:8000/queue/register
Content-Type: application/json

{
  "user": {
    "name": "Isabel Mucanda",
    "id_number": "00991122BO088",
    "phone": "+244923456789",
    "birth_date": "1995-04-12"
  },
  "biometric": {
    "biometric_id": "c13f9c04-1111-4bb8-9a7d-0e44fcd6b2c0",
    "finger_index": 1
  }
}

### Iniciar escaneamento biométrico
POST http://127.0.0.1:8000/queue/scan
Content-Type: application/json

{
  "biometric_id": "c13f9c04-6c88-4bb8-9a7d-0e44fcd6b2c0"
}

### Parte do frontend 
### Listar a fila
GET http://127.0.0.1:8000/queue/list

### Verificar usuário chamado (pendente de verificação)
GET http://127.0.0.1:8000/queue/called


### Verificar usuário em atendimento
GET http://127.0.0.1:8000/queue/current


### Consultar posição na fila
### Usando número de identificação
GET http://127.0.0.1:8000/queue/consult?id_number=9876563LA055

### Usando número de telefone
GET http://127.0.0.1:8000/queue/consult?phone=+244923456789


### Chamar o próximo da fila
PUT http://127.0.0.1:8000/queue/next

### Verificar usuário chamado
POST http://127.0.0.1:8000/biometrics/verify_called_user
Content-Type: application/json

{
  "queue_id":7,
  "biometric_id": "c13f9c04-0000-4bb8-9a7d-0e44fcd6b2c0"
}


### Pular o próximo da fila
PUT http://127.0.0.1:8000/queue/skip

### Finalizar atendimento
PUT http://127.0.0.1:8000/queue/done

### Listar auditorias
GET http://127.0.0.1:8000/audit/

### Verificar integridade da cadeia de auditoria
GET http://127.0.0.1:8000/audit/verify

### Verificar integridade de auditoria específica
GET http://127.0.0.1:8000/audit/verify/10

### Verificar sumário da cadeia de auditoria
GET http://127.0.0.1:8000/audit/verify-summary

### É necessário validar a integridade de um registo específico (record_hash)
