# Base Python 3.12 slim
FROM python:3.12-slim

ENV DEBIAN_FRONTEND=noninteractive

# Dependências do sistema
RUN apt-get update \
    && apt-get install -y build-essential libpq-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copia apenas os arquivos de requisitos para aproveitar cache
COPY requirements/*.txt ./

RUN pip install --no-cache-dir -r dev.txt

# Copia código da app
COPY ./app ./app

# Porta padrão dev
EXPOSE 8000

# Comando dev
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
