### Backend - Operadores
### Criar primeiro operador (bootstrap)
POST http://127.0.0.1:8000/api/v1/operators/bootstrap
Content-Type: application/json

{
  "username": "admin",
  "password": "123",
  "role": "admin"
}

###
GET http://127.0.0.1:8000/api/v1/operators/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwic3ViIjoiYWRtaW4iLCJpYXQiOjE3NzAzMTczMjEsImV4cCI6MTc3MDMxNzkyMSwianRpIjoiMzg4YWVlNjE2ZjNjNDJlN2I0MGQxYjYyZTg1MmRhOGEifQ.aV0Gs27RM2yLC1fm7Hgu5Z9sfbc1lp9hqNeA5s6y-So

### Login
POST http://127.0.0.1:8000/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123"
}

### Middleware - Biometria
### Parte do middleware C#

### Registrar usuário com biometria #2
POST http://127.0.0.1:8000/api/v1/queue/register 
Content-Type: application/json

{
  "user": {
    "name": "Ana Cristina Lima",
    "birth_date": "2000-03-22",
    "is_pregnant": false,
    "pregnant_until": null,
    "is_disabled_temp": false,
    "disabled_until": null,
    "document_id": "009834221LA012",
    "phone": "945678901"
  },
  "biometric": {
    "biometric_id": "e6f3a9d2-1b44-4c7e-8d96-fc1d5a2b9f3e",
    "finger_index": 4
  },
  "attendance_type": "urgent",
  "operator_id": 26
}

### Registrar usuário com biometria #3
POST http://127.0.0.1:8000/api/v1/queue/register 
Content-Type: application/json

{
  "user": {
    "name": "João da Silva",
    "birth_date": "1950-05-20",
    "is_pregnant": false,
    "pregnant_until": null,
    "is_disabled_temp": false,
    "disabled_until": null,
    "document_id": "003211990LA003",
    "phone": "912345678"
  },
  "biometric": {
    "biometric_id": "e6f3a9d2-1b44-4c7e-8d96-fc1d5a2b9f3e",
    "finger_index": 1
  },
  "attendance_type": "normal",
  "operator_id": 26
}




### Registrar usuário com biometria #4
POST http://127.0.0.1:8000/api/v1/queue/register 
Content-Type: application/json

{
  "user": {
    "name": "Luiz Alberto Fernandes",
    "birth_date": "1955-09-12",
    "is_pregnant": false,
    "pregnant_until": null,
    "is_disabled_temp": false,
    "disabled_until": null,
    "document_id": "001245678LA018",
    "phone": "956789012"
  },
  "biometric": {
    "biometric_id": "HASH_TESTE_DEDO_1"
  },
  "attendance_type": "priority",
  "operator_id": 26
}



### Entrada rapida na fila
POST http://127.0.0.1:8000/api/v1/biometrics/quick-entry
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzcwMTY0NTM2LCJzdWIiOiJhZG1pbiIsImlhdCI6MTc3MDE2MDkzNn0.MafUYUNg9xk3_YpFXLiHbB-dqjCvZIEeP72fX545t5E

{
  "biometric_id": "e6f3a9d2-1b44-4c7e-8d96-fc13e",
  "attendance_type": "normal"
}


### Autenticar user chamado
POST http://127.0.0.1:8000/api/v1/biometrics/authenticate
Content-Type: application/json

{
  "queue_item_id": 4,
  "biometric_hash": "ae046e6a2d025537ce34ca171d8241315866f85eae030c7eecae7c92d2c9a3c9",
  "call_token": "3939dbed-f64b-4eea-b749-bc89e7dea148",
  "operator_id": 26
}


### React Admin - Gestão da Fila

### Chamar o próximo da fila
POST http://127.0.0.1:8000/api/v1/queue/call-next

### Finalizar atendimento
POST http://127.0.0.1:8000/api/v1/queue/finish


### Cancelar atendimento
POST http://127.0.0.1:8000/api/v1/queue/cancel
Content-Type: application/json

{
  "item_id":1
}

### Reagendar
POST http://127.0.0.1:8000/api/v1/queue/requeue
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzYzOTE4MTYxLCJzdWIiOiJhZG1pbiIsImlhdCI6MTc2MzkxNDU2MX0.u_bZhBuTdBiAsxbaLm5q4ncYwlSOr7KzT9qLyJxfqZc

{
  "user_id": 3,
  "attendance_type": "urgent"
}

### Pular o próximo da fila
POST http://127.0.0.1:8000/api/v1/queue/skip


### React - Display Público 

### Listar a fila com usuários em espera e chamados em espera de verificação
GET http://127.0.0.1:8000/api/v1/queue/waiting-and-called


### Verificar usuário em atendimento
GET http://127.0.0.1:8000/api/v1/queue/current


### Parte do middleware C# (uso interno)
GET http://127.0.0.1:8000/api/v1/queue/next-called-for-client

################################ OLD | LEGACY ################################ 

### Consultar posição na fila
### Usando número de identificação
GET http://127.0.0.1:8000/queue/consult?id_number=9876563LA055

### Usando número de telefone
GET http://127.0.0.1:8000/queue/consult?phone=+244923456789




### Listar auditorias
GET http://127.0.0.1:8000/audit/

### Verificar integridade da cadeia de auditoria
GET http://127.0.0.1:8000/audit/verify

### Verificar integridade de auditoria específica
GET http://127.0.0.1:8000/audit/verify/10

### Verificar sumário da cadeia de auditoria
GET http://127.0.0.1:8000/audit/verify-summary

### É necessário validar a integridade de um registo específico (record_hash)
