### Backend - Operadores

GET http://127.0.0.1:8000/api/v1/operators/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwic3ViIjoiYWRtaW4iLCJpYXQiOjE3NzA0NzA5MjgsImV4cCI6MTc3MDQ3MTUyOCwianRpIjoiMTM5NTkwODc4NWQ3NGM5NTkyOTc2ODdlMjIwZDhiODcifQ.xgOkG9YqzW6Q539e8w7w9ZPPO0-nw8Ibzbg2MaRQhhU

### Login
POST http://127.0.0.1:8000/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123"
}

### Middleware - Biometria
### Parte do middleware C#

### Registrar usuário com biometria #2
POST http://127.0.0.1:8000/api/v1/queue/register 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwic3ViIjoiYWRtaW4iLCJpYXQiOjE3NzA1ODE1NjAsImV4cCI6MTc3MDU4MjE2MCwianRpIjoiNDBiNWQxYjE0YjUwNDM0YWEwYzEwZjVmYzY2M2NiNDIifQ.sok5crlWcNcKQBUl9h_XkGAV0Y52JEKZNGFv4CrEMnY

{
  "user": {
    "name": "Ana Cristina Lima",
    "birth_date": "2000-03-22",
    "is_pregnant": false,
    "pregnant_until": null,
    "is_disabled_temp": false,
    "disabled_until": null,
    "document_id": "009834221LA012",
    "phone": "945678901"
  },
  "credential": {
    "identifier": "e6f3a9d2-1b44-4c7e-8d96-fc1d5a2b9f3e"
  },
  "attendance_type": "urgent"
}

### Registrar usuário com biometria #3
POST http://127.0.0.1:8000/api/v1/queue/register 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwic3ViIjoiYWRtaW4iLCJpYXQiOjE3NzA1ODE1NjAsImV4cCI6MTc3MDU4MjE2MCwianRpIjoiNDBiNWQxYjE0YjUwNDM0YWEwYzEwZjVmYzY2M2NiNDIifQ.sok5crlWcNcKQBUl9h_XkGAV0Y52JEKZNGFv4CrEMnY

{
  "user": {
    "name": "João da Silva",
    "birth_date": "1950-05-20",
    "is_pregnant": false,
    "pregnant_until": null,
    "is_disabled_temp": false,
    "disabled_until": null,
    "document_id": "003211990LA003",
    "phone": "912345678"
  },
  "credential": {
    "identifier": "HASH_TESTE_DEDO_1"
  },
  "attendance_type": "normal"
}




### Registrar usuário com biometria #4
POST http://127.0.0.1:8000/api/v1/queue/register 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwic3ViIjoiYWRtaW4iLCJpYXQiOjE3NzA1ODE1NjAsImV4cCI6MTc3MDU4MjE2MCwianRpIjoiNDBiNWQxYjE0YjUwNDM0YWEwYzEwZjVmYzY2M2NiNDIifQ.sok5crlWcNcKQBUl9h_XkGAV0Y52JEKZNGFv4CrEMnY

{
  "user": {
    "name": "Luiz Alberto Fernandes",
    "birth_date": "1955-09-12",
    "is_pregnant": false,
    "pregnant_until": null,
    "is_disabled_temp": false,
    "disabled_until": null,
    "document_id": "001245678LA018",
    "phone": "956789012"
  },
  "credential": {
    "identifier": "HASH_TESTE_DEDO_2"
  },
  "attendance_type": "priority"
}



### Entrada rapida na fila
POST http://127.0.0.1:8000/api/v1/queue/quick-entry
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwic3ViIjoiYWRtaW4iLCJpYXQiOjE3NzA0ODA5OTcsImV4cCI6MTc3MDQ4MTU5NywianRpIjoiYWFkYjM2MmVhYTA0NDM4NzlhNDA0ZmNmZTMwZjQ5ZTUifQ.aJNWXv0pmwmOliwpMXrwMeJ3ZY8Jb8mOW0SAr2cAyVI

{
  "biometric_hash": "HASH_TESTE_DEDO_1",
  "attendance_type": "normal"
}


### Autenticar user chamado
POST http://127.0.0.1:8000/api/v1/biometrics/authenticate
Content-Type: application/json

{
  "queue_item_id": 3,
  "credential": "HASH_TESTE_DEDO_2",
  "call_token": "d37083d8-dbf5-47d9-8902-b7ae39c29e50",
  "operator_id": 1
}


### React Admin - Gestão da Fila

### Chamar o próximo da fila
POST http://127.0.0.1:8000/api/v1/queue/call-next

### Finalizar atendimento
POST http://127.0.0.1:8000/api/v1/queue/finish


### Cancelar atendimento
POST http://127.0.0.1:8000/api/v1/queue/cancel
Content-Type: application/json

{
  "item_id":1
}

### Reagendar
POST http://127.0.0.1:8000/api/v1/queue/requeue
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzYzOTE4MTYxLCJzdWIiOiJhZG1pbiIsImlhdCI6MTc2MzkxNDU2MX0.u_bZhBuTdBiAsxbaLm5q4ncYwlSOr7KzT9qLyJxfqZc

{
  "user_id": 3,
  "attendance_type": "urgent"
}

### Pular o próximo da fila
POST http://127.0.0.1:8000/api/v1/queue/skip


### React - Display Público 

### Listar a fila com usuários em espera e chamados em espera de verificação
GET http://127.0.0.1:8000/api/v1/queue/waiting-and-called


### Verificar usuário em atendimento
GET http://127.0.0.1:8000/api/v1/queue/current


### Parte do middleware C# (uso interno)
GET http://127.0.0.1:8000/api/v1/queue/next-called-for-client

################################ OLD | LEGACY ################################ 

### Consultar posição na fila
### Usando número de identificação
GET http://127.0.0.1:8000/queue/consult?id_number=9876563LA055

### Usando número de telefone
GET http://127.0.0.1:8000/queue/consult?phone=+244923456789




### Listar auditorias
GET http://127.0.0.1:8000/api/v1/audits/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImF1ZGl0b3IiLCJyb2xlIjoiYXVkaXRvciIsInN1YiI6ImF1ZGl0b3IiLCJpYXQiOjE3NzA0MTAzMjcsImV4cCI6MTc3MDQxMDkyNywianRpIjoiNTMxNWQxZDE4MjllNGFiMGI5MmVmMzJkZGYwZjhmMTMifQ.JbVz4dlWG9TAMuAVUG0LeBpSzhcJXEr_29aklsXN_6E

### Verificar integridade da cadeia de auditoria
GET http://127.0.0.1:8000/api/v1/audits/verify

### Verificar integridade de auditoria específica
GET http://127.0.0.1:8000/api/v1/audits/verify/1

### Verificar sumário da cadeia de auditoria
GET http://127.0.0.1:8000/api/v1/audits/verify-summary
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImF1ZGl0b3IiLCJyb2xlIjoiYXVkaXRvciIsInN1YiI6ImF1ZGl0b3IiLCJpYXQiOjE3NzA0MTAzMjcsImV4cCI6MTc3MDQxMDkyNywianRpIjoiNTMxNWQxZDE4MjllNGFiMGI5MmVmMzJkZGYwZjhmMTMifQ.JbVz4dlWG9TAMuAVUG0LeBpSzhcJXEr_29aklsXN_6E
